### ISSUE TITLE
Remove Live tag on last elections

### ISSUE THREAD

**Issue by overeha** [code4romania/rezultate-vot-client#81]
Please remove the live tag on the 2020 local elections

![image](https://user-images.githubusercontent.com/45068169/94853765-8b7d7e80-0434-11eb-9ed3-badd9371e81b.png)

**Comment by dapetcu21** [comment]
@thewindev? Or someone else with db access?

**Comment by thewindev** [comment]
We need the "live" flag for the moment because we retrieve these results in another way(downloading live data from BEC instead of retrieving it from the database), so it will break the backend. It's better to hide it in the UI for now, just until the results are final and we populate the database with them.

**Comment by RaduCStefanescu** [comment]
Should we keep the `live` tag until we have the final results?
And then remove it.

**Comment by thewindev** [comment]
Until we have the final results and the database is populated with them. Also, we'll have a second round, will we add the live tag again when that happens?

**Comment by dapetcu21** [comment]
@thewindev Only for the ballots for the second round, I guess. That sounds semantically correct. Let me check if the frontend handles this well.

**Comment by dapetcu21** [comment]
It doesn't. but it's an easy fix.

**Comment by dapetcu21** [comment]
https://github.com/code4romania/reusable-components/pull/76/files

**Comment by RaduCStefanescu** [comment]
I think we can close this one.
